---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots

today we're making interactive plots in plotly. We will make examples using the NYC airbnb dataset.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial cleaning / subsetting
```{r}
nyc_airbnb = nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(rating, neighbourhood_group, neighbourhood,room_type, lat, long, price) |>
  drop_na(rating) |>
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

Use plotly to make some quick plots.\
(the plots that you can interact with)
```{r}
nyc_airbnb |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price", price, "\nNeighborhood:", neighbourhood)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label, 
    type = "scatter", mode = "markers", alpha = 0.5
  )
```















